### ISSUE TITLE
Adapt new experiments into framework

### ISSUE THREAD

**Issue by aaronspring** [aaronspring/pymistral#4]
- [x] CMIP5
- [x] CMIP6
- [x] GE
- [ ] configurable personal experiments (for now my perfect-model framework)

via yaml files maybe?
https://intake-cesm.readthedocs.io/en/latest/getting-started.html
or just mistral locations?

**Comment by aaronspring** [comment]
https://github.com/ContinuumIO/intake/tree/master/examples/precip  Gutes Beispiel.

**Comment by aaronspring** [comment]
CMIP5 zum runterladen, evtl auch CMIP6 soon? https://climate-cms.org/2018/08/16/search-cmip5-data-interactively.html

**Comment by seb-1** [comment]
DKRZ betreibt Notebook server mit Zugang zu CMIP5, GE ist auch darüber verfügbar. https://ecaslab.dkrz.de/home.html

Im Hintergrund greift das auf /work/kd0956 zu, GE liegt in /work/kd0956/External

**Comment by aaronspring** [comment]
https://github.com/pangeo-data/esgf2xarray @seb-1 das sieht mir am vielversprechendsten aus

**Comment by aaronspring** [comment]
esgf2xarray hab das example nachgemacht. funktioniert. krass.

**Comment by aaronspring** [comment]
https://github.com/NCAR/intake-esm/pull/52
