### ISSUE TITLE
conda environment for mistral

### ISSUE THREAD

**Issue by seb-1** [aaronspring/pymistral#7]
Create and maintain a .yml file with an environment that allows to run all code in this project and allows to start jupyterlab with the start-jupyter.sh from DKRZ.

**Comment by aaronspring** [comment]
funktioniert

**Comment by aaronspring** [comment]
ich wuerde vorschlagen, dass wir ein environment zum testen haben (minimal ausstattung) und eine fuer mistral wenn wir interaktiv arbeiten (dann mit jupyter lab extensions und allem schnickschnack!)
